---
- name: "Get daily COVID-19 report from John Hopkins University, but we use previous day as file reference."
  get_url:
    url: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/{{ dataset_filename }}
    dest: /tmp/{{ dataset_filename }}

- name: "We can do grep, python would be best for data cleanup, but what about ansible module for handling CSV;-)"
  read_csv:
    path: /tmp/{{ dataset_filename }}
    key: Combined_Key
  register: Region

- name: 'Archive dataset to S3'
  aws_s3:
    bucket: "{{ s3_bucket }}"
    permission: public-read
    object: /archive/covid-19/{{ dataset_filename }}
    src: /tmp/{{ dataset_filename }}
    mode: put

- name: 'Create HTML from template.'
  template:
    dest: /tmp/covid-19.html
    src: covid-19.html

- name: 'Publish Page in S3'
  aws_s3:
    bucket: "{{ s3_bucket }}"
    permission: public-read
    object: index.html
    src: /tmp/covid-19.html
    mode: put
